version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  restaurant_service:
    build: ./restaurant_service
    ports:
      - "8081:8080"

  reservation_service:
    build: ./reservation_service
    ports:
      - "8082:8080"

  RRS-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: RRSpassword
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
